ALTER TABLE pois DROP COLUMN IF EXISTS updated_at;
ALTER TABLE pois DROP COLUMN IF EXISTS created_at;
ALTER TABLE pois DROP COLUMN IF EXISTS source;
ALTER TABLE pois DROP COLUMN IF EXISTS created_by;

ALTER TABLE buildings DROP COLUMN IF EXISTS source;
ALTER TABLE buildings DROP COLUMN IF EXISTS created_by;

DROP TABLE IF EXISTS map_features;
DROP FUNCTION IF EXISTS feature_geom(TEXT);
